In [1]:
import pandas as pd
df = pd.read_csv(r"E:/customer_behaviour.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55.0,M,Shirt,Clothing,4031,Pune,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Cash,Fortnightly
1,2,19.0,Female,Kurta,Clothing,4945,varanasi,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50.0,Female,Saree,Clothing,5460,Surat,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Net Banking,Weekly
3,4,21.0,Male,Shoes,Footwear,6894,CHANDIGARH,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,GOOGLE PAY,Weekly
4,5,45.0,Male,Jeans,Clothing,3874,Ahmedabad,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,Debit Card,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3843 non-null   float64
 2   Gender                  3843 non-null   str
 3   Item Purchased          3843 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3843 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3804 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3841 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(2), int64(3), str(13)
memory usage: 548.6 KB

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3843.000000,3843,3843,3900,3900.000000,3843,3900,3900,3900,3804.000000,3900,3900,3900,3900,3900.000000,3841,3900
unique,NaN,NaN,7,27,4,NaN,100,4,25,4,NaN,2,6,2,2,NaN,33,7
top,NaN,NaN,Male,Jacket,Clothing,NaN,Nagpur,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,Paytm,Every 3 Months
freq,NaN,NaN,1565,322,1737,NaN,102,1754,176,999,NaN,2846,677,2223,2223,NaN,361,585
mean,1950.847179,44.033568,NaN,NaN,NaN,5497.099487,NaN,NaN,NaN,NaN,3.748922,NaN,NaN,NaN,NaN,25.379744,NaN,NaN
std,1127.147545,15.211922,NaN,NaN,NaN,31920.096040,NaN,NaN,NaN,NaN,0.717155,NaN,NaN,NaN,NaN,14.455480,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,-500.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,973.750000,31.000000,NaN,NaN,NaN,2882.500000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,4507.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2926.500000,57.000000,NaN,NaN,NaN,6054.250000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,999999.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                       57
Gender                    57
Item Purchased            57
Category                   0
Purchase Amount (USD)      0
Location                  57
Size                       0
Color                      0
Season                     0
Review Rating             96
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method            59
Frequency of Purchases     0
dtype: int64

In [6]:

df["Age"] = df["Age"].fillna(df["Age"].median())


df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(
    lambda x: x.fillna(x.median())
)
df["Review Rating"] = df["Review Rating"].fillna(df["Review Rating"].median())


categorical_cols = ["Gender", "Item Purchased", "Location", "Payment Method"]

for col in categorical_cols:
    if col in df.columns and df[col].isnull().sum() > 0:
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)


print(df.isnull().sum())

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [9]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [10]:
df[['age','age_group']].head(10)

    age    age_group
0  55.0  Middle-aged
1  19.0  Young Adult
2  50.0  Middle-aged
3  21.0  Young Adult
4  45.0  Middle-aged
5  46.0  Middle-aged
6  63.0       Senior
7  27.0  Young Adult
8  26.0  Young Adult
9  57.0  Middle-aged

In [11]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [12]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [13]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [14]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [15]:
df = df.drop('promo_code_used', axis=1)

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [17]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
from sqlalchemy import create_engine
username = "root"
password = "singh2026"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55.0,M,Shirt,Clothing,4031,Pune,L,Gray,Winter,3.1,Yes,Express,Yes,14,Cash,Fortnightly,Middle-aged,14
1,2,19.0,Female,Kurta,Clothing,4945,varanasi,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50.0,Female,Saree,Clothing,5460,Surat,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Net Banking,Weekly,Middle-aged,7
3,4,21.0,Male,Shoes,Footwear,6894,CHANDIGARH,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,GOOGLE PAY,Weekly,Young Adult,7
4,5,45.0,Male,Jeans,Clothing,3874,Ahmedabad,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,Debit Card,Annually,Middle-aged,365

In [19]:
import numpy as np

gender_mapping = {
    'm': 'Male', 'M': 'Male', 'male': 'Male',
    'f': 'Female', 'F': 'Female', 'female': 'Female'
}
df['gender'] = df['gender'].replace(gender_mapping)

mask = df['gender'].str.lower() == 'other'
if mask.any():
    df.loc[mask, 'gender'] = np.random.choice(['Male', 'Female'], size=mask.sum())

In [20]:
print(df['gender'].value_counts(dropna=False))

gender
Male      2205
Female    1695
Name: count, dtype: int64

In [21]:
import pandas as pd
import random
from sqlalchemy import create_engine

gender_mapping = {
    'm': 'Male', 'M': 'Male', 'male': 'Male',
    'f': 'Female', 'F': 'Female', 'female': 'Female'
}
df['gender'] = df['gender'].replace(gender_mapping)

mask = df['gender'].str.lower() == 'other'
if mask.any():
    df.loc[mask, 'gender'] = [random.choice(['Male', 'Female']) for _ in range(mask.sum())]

username = "root"
password = "singh2026"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
df.to_sql("customer", engine, if_exists="replace", index=False)

print(df['gender'].value_counts(dropna=False))

gender
Male      2205
Female    1695
Name: count, dtype: int64

In [22]:
pd.read_sql("""
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
""", engine)

   gender     revenue
0  Female   8606539.0
1    Male  12832149.0

In [24]:
pd.read_sql("""
SELECT customer_id, purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
""", engine)

     customer_id  purchase_amount
0              4             6894
1              7             6520
2              9             7344
3             16             5946
4             20             6904
..           ...              ...
544         1656             6013
545         1662             6467
546         1676             6873
547          957             7301
548          889             5674

[549 rows x 2 columns]

In [25]:
pd.read_sql("""
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5
""", engine)

  item_purchased  Average Product Rating
0          Shoes                    3.89
1          Kurta                    3.87
2       Sneakers                    3.83
3        Sandals                    3.81
4            Cap                    3.80

In [26]:
pd.read_sql("""
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
""", engine)

  shipping_type  avg_purchase_amount
0       Express              4539.56
1      Standard              4369.39

In [27]:
pd.read_sql("""
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC
""", engine)

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2846    5534.21     15750367.0
1                 Yes             1054    5396.89      5688321.0

In [28]:
pd.read_sql("""
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5
""", engine)

  item_purchased  discount_rate
0     Sunglasses          49.60
1           Coat          49.07
2        Loafers          47.73
3           Belt          47.54
4        Mojaris          47.50

In [33]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer
GROUP BY customer_segment
""", engine)

  customer_segment  Number_of_Customers
0            Loyal                 3116
1              New                   84
2        Returning                  700

In [38]:
pd.read_sql("""
SELECT category, item_purchased, COUNT(customer_id) AS total_orders
FROM customer
GROUP BY category, item_purchased
ORDER BY category, COUNT(customer_id) DESC
""", engine)

       category item_purchased  total_orders
0   Accessories       Backpack           161
1   Accessories          Shawl           154
2   Accessories          Scarf           153
3   Accessories         Wallet           136
4   Accessories          Watch           134
5   Accessories     Sunglasses           125
6   Accessories           Belt           122
7   Accessories            Cap           120
8   Accessories        Handbag           114
9   Accessories         Jacket            17
10     Clothing         Jacket           190
11     Clothing          Kurta           186
12     Clothing        T-Shirt           183
13     Clothing       Trousers           179
14     Clothing          Shirt           176
15     Clothing          Kurti           174
16     Clothing     Ethnic Top           172
17     Clothing          Jeans           164
18     Clothing          Saree           157
19     Clothing        Lehenga           156
20     Footwear       Slippers            93
21     Footwear       Sneakers            89
22     Footwear        Loafers            88
23     Footwear          Shoes            85
24     Footwear          Boots            82
25     Footwear        Mojaris            80
26     Footwear        Sandals            77
27     Footwear         Jacket             7
28    Outerwear         Jacket           165
29    Outerwear           Coat           161

In [42]:
pd.read_sql("""
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
""", engine)

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            959

In [40]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN age < 25 THEN 'Under 25'
        WHEN age BETWEEN 25 AND 39 THEN '25-39'
        WHEN age BETWEEN 40 AND 59 THEN '40-59'
        ELSE '60+' 
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC
""", engine)

  age_group  total_revenue
0  Under 25      6574915.0
1     40-59      5349233.0
2       60+      5096600.0
3     40-59      4417940.0